image: atlassian/pipelines-awscli

pipelines:
  custom:
    aws_ass_stop:
      - step:
          name: Delete all CloudFormation Stacks that have the tag stack_deletion_order
          script:
            - >
              aws ecs run-task \
                --task-definition task-aws-ass-stop \
                --cluster ${ECS_MGMT_CLUSTER} \
                --network-configuration "awsvpcConfiguration={subnets=[${SUBNET}],securityGroups=[${SG}]}" \
                --launch-type "FARGATE"

