image: atlassian/pipelines-awscli

pipelines:
  custom:
    aws_ass_start:
      - step:
          name: Create all deleted CloudFormation Stacks that have the tag stack_deletion_order
          script:
            - >
              aws ecs run-task \
                --task-definition task-aws-ass-start \
                --cluster ${ECS_MGMT_CLUSTER} \
                --network-configuration "awsvpcConfiguration={subnets=[${SUBNET}],securityGroups=[${SG}]}" \
                --launch-type "FARGATE" \
                --overrides "{\"containerOverrides\": [{\"name\": \"aws-ass-start\", \"environment\": [{\"name\": \"CHATURL\", \"value\": \"${CHATURL}\"}, {\"name\": \"ECS_MGMT_CLUSTER\", \"value\": \"${ECS_MGMT_CLUSTER}\"}]}]}"
