image: python:3.6

pipelines:
  branches:
    master:
      - step:
          name: Build and push Docker deploy image
          script:
            - git clone https://github.com/rik2803/bb-aws-utils.git
            - bb-aws-utils/build-and-push-docker-image.bash
            - bb-aws-utils/deploy-docker-image.bash

options:
  docker: true
