#
# 2016 (c) IxorTalk CVBA
# All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of IxorTalk CVBA
#
# The intellectual and technical concepts contained
# herein are proprietary to IxorTalk CVBA
# and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from IxorTalk CVBA.
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.
#

image: atlassian/default-image:2

pipelines:
  pull-requests:
    '**':
      - step:
          name: Pull Request Check
          image: atlassian/default-image:2
          caches:
            - maven
          script:
            - git clone -b ${BB_AWS_UTILS_VERSION} https://github.com/rik2803/bb-aws-utils.git
            - export LIB_DIR="./bb-aws-utils/lib"
            - source bb-aws-utils/lib/load.bash
            - export MAVEN_DEVELOP_COMMAND="clean compile -DskipDocker"
            - maven_build
  custom:
    deploy-to-tst:
      - step:
          name: Snapshot build and deploy to tst
          image: atlassian/default-image:2
          caches:
            - maven
          script:
            - ssh git@bitbucket.org
            - git clone -b ${IXORTALK_CICD_VERSION:-master} git@bitbucket.org:ixorcvba/ixortalk.cicdtools.git
            - source ixortalk.cicdtools/lib.bash
            - ixortalk_build_and_deploy
    build-and-push-to-docker-hub:
      - step:
          name: Builds an image and pushes it to Docker Hub only
          image: atlassian/default-image:2
          caches:
            - maven
          script:
            - git clone -b ${BB_AWS_UTILS_VERSION} https://github.com/rik2803/bb-aws-utils.git
            - export LIB_DIR="./bb-aws-utils/lib"
            - source bb-aws-utils/lib/load.bash
            - export MAVEN_DEVELOP_COMMAND="clean deploy"
            - maven_build
  branches:
    master:
      - step:
          name: Release build and deploy to stg
          image: atlassian/default-image:2
          caches:
            - maven
          script:
            - git clone -b ${IXORTALK_CICD_VERSION:-master} git@bitbucket.org:ixorcvba/ixortalk.cicdtools.git
            - source ixortalk.cicdtools/lib.bash
            - ixortalk_release_build_and_deploy

options:
  docker: true
